image: node:18

include:
  - project: 'fr/ci'
    ref: main
    file: 'ssh.ci.yml'

stages:
  - deploy-dev

deploy-to-test-server:
  stage: deploy-dev
  extends: .install-ssh
  variables:
    SSH_PRIVATE_KEY: $TEST_SSH_PRIVATE_KEY
    SERVER_KNOWN_HOSTS: $TEST_SERVER_KNOWN_HOSTS
  script:
    - npm install
    - npm run build
    - rsync --delete -avz --progress -e "ssh -p $TEST_SERVER_PORT" dist/ $TEST_SERVER_USER@$TEST_SERVER_HOST:www/front.friendlee.pro/rodnya/
  only:
    - dev
  tags:
    - nodejs
  environment:
    name: test
    url: https://front.friendlee.pro/rodnya
